// @ts-check

/**
 * Sidebar for the API reference. Every feature folder is auto-generated from
 * `docs/api/<folder>`; folders are grouped by what the reader is trying to do.
 * Ⓔ marks features that require a Countly Enterprise license.
 */

const dir = (label, dirName) => ({
  type: 'category',
  label,
  items: [{ type: 'autogenerated', dirName: `api/${dirName}` }],
});

const group = (label, items) => ({
  type: 'category',
  label,
  items,
});

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  apiSidebar: [
    { type: 'doc', id: 'api/index', label: 'Overview' },
    group('Core API', [
      dir('Data Ingestion', 'core/bulk'),
      dir('Analytics', 'core/analytics'),
      dir('Events', 'core/events'),
      dir('Event Groups', 'core/event-groups'),
      dir('App Users', 'core/app-users'),
      dir('Apps', 'core/apps'),
      dir('User Management', 'core/users'),
      dir('Token', 'core/token'),
      dir('Tasks', 'core/tasks'),
      dir('Export', 'core/export'),
      dir('Notes', 'core/notes'),
      dir('Date Presets', 'core/date-presets'),
      dir('CMS', 'core/cms'),
      dir('Render', 'core/render'),
      dir('SDK', 'sdk'),
      dir('Plugins', 'plugins'),
      {
        type: 'category',
        label: 'System Core',
        items: [
          { type: 'autogenerated', dirName: 'api/core/system' },
          { type: 'autogenerated', dirName: 'api/core/ping' },
          { type: 'autogenerated', dirName: 'api/core/countly' },
        ],
      },
    ]),
    group('Analytics & Insights', [
      dir('Drill Ⓔ', 'drill'),
      dir('Funnels Ⓔ', 'funnels'),
      dir('Flows Ⓔ', 'flows'),
      dir('Cohorts Ⓔ', 'cohorts'),
      dir('Formulas Ⓔ', 'formulas'),
      dir('Retention Segments Ⓔ', 'retention_segments'),
      dir('Active Users Ⓔ', 'active_users'),
      dir('Concurrent Users Ⓔ', 'concurrent_users'),
      dir('Activity Map Ⓔ', 'activity-map'),
      dir('Users Ⓔ', 'users'),
      dir('Revenue Ⓔ', 'revenue'),
      dir('Attribution Ⓔ', 'attribution'),
      dir('Adjust Ⓔ', 'adjust'),
      dir('AppsFlyer Ⓔ', 'appsflyer'),
      dir('Performance Monitoring Ⓔ', 'performance-monitoring'),
      dir('Geo Ⓔ', 'geo'),
      dir('Views', 'views'),
      dir('Times of Day', 'times-of-day'),
      dir('Slipping Away Users', 'slipping-away-users'),
      dir('Compare', 'compare'),
      dir('Browser', 'browser'),
      dir('Density', 'density'),
      dir('Locale', 'locale'),
      dir('Sources', 'sources'),
    ]),
    group('User Engagement', [
      dir('Push', 'push'),
      dir('Push Approver Ⓔ', 'push_approver'),
      dir('Surveys Ⓔ', 'surveys'),
      dir('Star Rating', 'star-rating'),
      dir('Remote Config', 'remote-config'),
      dir('AB Testing Ⓔ', 'ab-testing'),
      dir('Content Ⓔ', 'content'),
      dir('Journey Engine Ⓔ', 'journey_engine'),
      dir('AI Assistants Ⓔ', 'ai-assistants'),
      dir('Guides', 'guides'),
    ]),
    group('Crashes & Errors', [
      dir('Crashes', 'crashes'),
      dir('Crash Symbolication Ⓔ', 'crash_symbolication'),
      dir('Crashes Jira Ⓔ', 'crashes-jira'),
      dir('Error Logs', 'errorlogs'),
    ]),
    group('Security & Access', [
      dir('LDAP Ⓔ', 'ldap'),
      dir('Active Directory Ⓔ', 'active_directory'),
      dir('OIDC Ⓔ', 'oidc'),
      dir('Okta Ⓔ', 'okta'),
      dir('Cognito Ⓔ', 'cognito'),
      dir('Two Factor Auth', 'two-factor-auth'),
      dir('reCAPTCHA', 'recaptcha'),
      dir('Block Ⓔ', 'block'),
      dir('Groups Ⓔ', 'groups'),
      dir('Compliance Hub', 'compliance-hub'),
      dir('License Ⓔ', 'license'),
      dir('White Labeling Ⓔ', 'white-labeling'),
    ]),
    group('Data & Infrastructure', [
      dir('ClickHouse', 'clickhouse'),
      dir('Kafka', 'kafka'),
      dir('Data Manager Ⓔ', 'data-manager'),
      dir('Config Transfer Ⓔ', 'config-transfer'),
      dir('DBViewer', 'dbviewer'),
      dir('Hooks', 'hooks'),
      dir('Populator', 'populator'),
      dir('Server Stats', 'server-stats'),
      dir('System Logs', 'systemlogs'),
      dir('System Utility', 'system-utility'),
      dir('Logger', 'logger'),
    ]),
    group('Dashboards & Reporting', [
      dir('Dashboards', 'dashboards'),
      dir('Alerts', 'alerts'),
      dir('Reports', 'reports'),
    ]),
  ],
};

module.exports = sidebars;
