/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar or table of contents for each doc
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  apiSidebar: [
    {
      type: 'category',
      label: 'API Documentation',
      items: [
        {
          type: 'doc',
          id: 'api/index',
          label: 'Overview',
        },
        {
          type: 'category',
          label: 'Analytics',
          items: [{ type: 'autogenerated', dirName: 'api/core/analytics' }],
        },
        {
          type: 'category',
          label: 'App Users',
          items: [{ type: 'autogenerated', dirName: 'api/core/app-users' }],
        },
        {
          type: 'category',
          label: 'Apps',
          items: [{ type: 'autogenerated', dirName: 'api/core/apps' }],
        },
        {
          type: 'category',
          label: 'Bulk',
          items: [{ type: 'autogenerated', dirName: 'api/core/bulk' }],
        },
        {
          type: 'category',
          label: 'CMS',
          items: [{ type: 'autogenerated', dirName: 'api/core/cms' }],
        },
        {
          type: 'category',
          label: 'Date Presets',
          items: [{ type: 'autogenerated', dirName: 'api/core/date-presets' }],
        },
        {
          type: 'category',
          label: 'Event Groups',
          items: [{ type: 'autogenerated', dirName: 'api/core/event-groups' }],
        },
        {
          type: 'category',
          label: 'Events',
          items: [{ type: 'autogenerated', dirName: 'api/core/events' }],
        },
        {
          type: 'category',
          label: 'Export',
          items: [{ type: 'autogenerated', dirName: 'api/core/export' }],
        },
        {
          type: 'category',
          label: 'Notes',
          items: [{ type: 'autogenerated', dirName: 'api/core/notes' }],
        },
        {
          type: 'category',
          label: 'Render',
          items: [{ type: 'autogenerated', dirName: 'api/core/render' }],
        },
        {
          type: 'category',
          label: 'Core SDK',
          items: [{ type: 'autogenerated', dirName: 'api/core/sdk' }],
        },
        {
          type: 'category',
          label: 'System Core',
          items: [
            { type: 'autogenerated', dirName: 'api/core/system' },
            { type: 'autogenerated', dirName: 'api/core/ping' },
            { type: 'autogenerated', dirName: 'api/core/countly' },
          ],
        },
        {
          type: 'category',
          label: 'Tasks',
          items: [{ type: 'autogenerated', dirName: 'api/core/tasks' }],
        },
        {
          type: 'category',
          label: 'Token',
          items: [{ type: 'autogenerated', dirName: 'api/core/token' }],
        },
        {
          type: 'category',
          label: 'User Management',
          items: [{ type: 'autogenerated', dirName: 'api/core/users' }],
        },
        {
          type: 'category',
          label: 'AB Testing Ⓔ',
          items: [{ type: 'autogenerated', dirName: 'api/ab-testing' }],
        },
        {
          type: 'category',
          label: 'Active Directory Ⓔ',
          items: [{ type: 'autogenerated', dirName: 'api/active_directory' }],
        },
        {
          type: 'category',
          label: 'Active Users Ⓔ',
          items: [{ type: 'autogenerated', dirName: 'api/active_users' }],
        },
        {
          type: 'category',
          label: 'Activity Map Ⓔ',
          items: [{ type: 'autogenerated', dirName: 'api/activity-map' }],
        },
        {
          type: 'category',
          label: 'Adjust Ⓔ',
          items: [{ type: 'autogenerated', dirName: 'api/adjust' }],
        },
        {
          type: 'category',
          label: 'AI Assistants Ⓔ',
          items: [{ type: 'autogenerated', dirName: 'api/ai-assistants' }],
        },
        {
          type: 'category',
          label: 'Alerts',
          items: [{ type: 'autogenerated', dirName: 'api/alerts' }],
        },
        {
          type: 'category',
          label: 'Block Ⓔ',
          items: [{ type: 'autogenerated', dirName: 'api/block' }],
        },
        {
          type: 'category',
          label: 'Browser',
          items: [{ type: 'autogenerated', dirName: 'api/browser' }],
        },
        {
          type: 'category',
          label: 'ClickHouse',
          items: [{ type: 'autogenerated', dirName: 'api/clickhouse' }],
        },
        {
          type: 'category',
          label: 'Cognito Ⓔ',
          items: [{ type: 'autogenerated', dirName: 'api/cognito' }],
        },
        {
          type: 'category',
          label: 'Cohorts Ⓔ',
          items: [{ type: 'autogenerated', dirName: 'api/cohorts' }],
        },
        {
          type: 'category',
          label: 'Compare',
          items: [{ type: 'autogenerated', dirName: 'api/compare' }],
        },
        {
          type: 'category',
          label: 'Compliance Hub',
          items: [{ type: 'autogenerated', dirName: 'api/compliance-hub' }],
        },
        {
          type: 'category',
          label: 'Concurrent Users Ⓔ',
          items: [{ type: 'autogenerated', dirName: 'api/concurrent_users' }],
        },
        {
          type: 'category',
          label: 'Config Transfer Ⓔ',
          items: [{ type: 'autogenerated', dirName: 'api/config-transfer' }],
        },
        {
          type: 'category',
          label: 'Content Ⓔ',
          items: [{ type: 'autogenerated', dirName: 'api/content' }],
        },
        {
          type: 'category',
          label: 'Crash Symbolication Ⓔ',
          items: [{ type: 'autogenerated', dirName: 'api/crash_symbolication' }],
        },
        {
          type: 'category',
          label: 'Crashes',
          items: [{ type: 'autogenerated', dirName: 'api/crashes' }],
        },
        {
          type: 'category',
          label: 'Crashes Jira Ⓔ',
          items: [{ type: 'autogenerated', dirName: 'api/crashes-jira' }],
        },
        {
          type: 'category',
          label: 'Dashboards',
          items: [{ type: 'autogenerated', dirName: 'api/dashboards' }],
        },
        {
          type: 'category',
          label: 'Data Manager Ⓔ',
          items: [{ type: 'autogenerated', dirName: 'api/data-manager' }],
        },
        {
          type: 'category',
          label: 'Data Migration',
          items: [{ type: 'autogenerated', dirName: 'api/data_migration' }],
        },
        {
          type: 'category',
          label: 'DBViewer',
          items: [{ type: 'autogenerated', dirName: 'api/dbviewer' }],
        },
        {
          type: 'category',
          label: 'Density',
          items: [{ type: 'autogenerated', dirName: 'api/density' }],
        },
        {
          type: 'category',
          label: 'Drill Ⓔ',
          items: [{ type: 'autogenerated', dirName: 'api/drill' }],
        },
        {
          type: 'category',
          label: 'Error Logs',
          items: [{ type: 'autogenerated', dirName: 'api/errorlogs' }],
        },
        {
          type: 'category',
          label: 'Flows Ⓔ',
          items: [{ type: 'autogenerated', dirName: 'api/flows' }],
        },
        {
          type: 'category',
          label: 'Formulas Ⓔ',
          items: [{ type: 'autogenerated', dirName: 'api/formulas' }],
        },
        {
          type: 'category',
          label: 'Funnels Ⓔ',
          items: [{ type: 'autogenerated', dirName: 'api/funnels' }],
        },
        {
          type: 'category',
          label: 'Geo Ⓔ',
          items: [{ type: 'autogenerated', dirName: 'api/geo' }],
        },
        {
          type: 'category',
          label: 'Groups Ⓔ',
          items: [{ type: 'autogenerated', dirName: 'api/groups' }],
        },
        {
          type: 'category',
          label: 'Guides',
          items: [{ type: 'autogenerated', dirName: 'api/guides' }],
        },
        {
          type: 'category',
          label: 'Hooks',
          items: [{ type: 'autogenerated', dirName: 'api/hooks' }],
        },
        {
          type: 'category',
          label: 'Journey Engine Ⓔ',
          items: [{ type: 'autogenerated', dirName: 'api/journey_engine' }],
        },
        {
          type: 'category',
          label: 'Kafka',
          items: [{ type: 'autogenerated', dirName: 'api/kafka' }],
        },
        {
          type: 'category',
          label: 'LDAP Ⓔ',
          items: [{ type: 'autogenerated', dirName: 'api/ldap' }],
        },
        {
          type: 'category',
          label: 'License Ⓔ',
          items: [{ type: 'autogenerated', dirName: 'api/license' }],
        },
        {
          type: 'category',
          label: 'Locale',
          items: [{ type: 'autogenerated', dirName: 'api/locale' }],
        },
        {
          type: 'category',
          label: 'Logger',
          items: [{ type: 'autogenerated', dirName: 'api/logger' }],
        },
        {
          type: 'category',
          label: 'OIDC Ⓔ',
          items: [{ type: 'autogenerated', dirName: 'api/oidc' }],
        },
        {
          type: 'category',
          label: 'Okta Ⓔ',
          items: [{ type: 'autogenerated', dirName: 'api/okta' }],
        },
        {
          type: 'category',
          label: 'Plugins',
          items: [{ type: 'autogenerated', dirName: 'api/plugins' }],
        },
        {
          type: 'category',
          label: 'Populator',
          items: [{ type: 'autogenerated', dirName: 'api/populator' }],
        },
        {
          type: 'category',
          label: 'Push',
          items: [{ type: 'autogenerated', dirName: 'api/push' }],
        },
        {
          type: 'category',
          label: 'Push Approver Ⓔ',
          items: [{ type: 'autogenerated', dirName: 'api/push_approver' }],
        },
        {
          type: 'category',
          label: 'reCAPTCHA',
          items: [{ type: 'autogenerated', dirName: 'api/recaptcha' }],
        },
        {
          type: 'category',
          label: 'Remote Config',
          items: [{ type: 'autogenerated', dirName: 'api/remote-config' }],
        },
        {
          type: 'category',
          label: 'Reports',
          items: [{ type: 'autogenerated', dirName: 'api/reports' }],
        },
        {
          type: 'category',
          label: 'Retention Segments Ⓔ',
          items: [{ type: 'autogenerated', dirName: 'api/retention_segments' }],
        },
        {
          type: 'category',
          label: 'Revenue Ⓔ',
          items: [{ type: 'autogenerated', dirName: 'api/revenue' }],
        },
        {
          type: 'category',
          label: 'SDK',
          items: [{ type: 'autogenerated', dirName: 'api/sdk' }],
        },
        {
          type: 'category',
          label: 'Server Stats',
          items: [{ type: 'autogenerated', dirName: 'api/server-stats' }],
        },
        {
          type: 'category',
          label: 'Slipping Away Users',
          items: [{ type: 'autogenerated', dirName: 'api/slipping-away-users' }],
        },
        {
          type: 'category',
          label: 'Sources',
          items: [{ type: 'autogenerated', dirName: 'api/sources' }],
        },
        {
          type: 'category',
          label: 'Star Rating',
          items: [{ type: 'autogenerated', dirName: 'api/star-rating' }],
        },
        {
          type: 'category',
          label: 'Surveys Ⓔ',
          items: [{ type: 'autogenerated', dirName: 'api/surveys' }],
        },
        {
          type: 'category',
          label: 'System Logs',
          items: [{ type: 'autogenerated', dirName: 'api/systemlogs' }],
        },
        {
          type: 'category',
          label: 'System Utility',
          items: [{ type: 'autogenerated', dirName: 'api/system-utility' }],
        },
        {
          type: 'category',
          label: 'Times of Day',
          items: [{ type: 'autogenerated', dirName: 'api/times-of-day' }],
        },
        {
          type: 'category',
          label: 'Two Factor Auth',
          items: [{ type: 'autogenerated', dirName: 'api/two-factor-auth' }],
        },
        {
          type: 'category',
          label: 'Users Ⓔ',
          items: [{ type: 'autogenerated', dirName: 'api/users' }],
        },
        {
          type: 'category',
          label: 'Views',
          items: [{ type: 'autogenerated', dirName: 'api/views' }],
        },
        {
          type: 'category',
          label: 'White Labeling Ⓔ',
          items: [{ type: 'autogenerated', dirName: 'api/white-labeling' }],
        },
        {
          type: 'category',
          label: 'Core Docs (Synced)',
          items: [{ type: 'autogenerated', dirName: 'core' }],
        },
        {
          type: 'category',
          label: 'Core Plugin Docs (Synced)',
          items: [{ type: 'autogenerated', dirName: 'core/plugins' }],
        },
        {
          type: 'category',
          label: 'Enterprise Plugin Docs (Synced)',
          items: [{ type: 'autogenerated', dirName: 'plugins' }],
        },
      ],
    },
  ],
};

module.exports = sidebars;
